parameters:
- name: PackageApp
  displayName: Package App
  type: boolean
  default: false

- name: PackageACTests
  displayName: Package Acceptance Tests
  type: boolean
  default: false

- name: PackageNuget
  displayName: Package Nuget Project
  type: boolean
  default: true

- name: RunUnitTests
  displayName: Run Unit Tests
  type: boolean
  default: true

- name: RunIntegTests
  displayName: Run Integration Tests
  type: boolean
  default: false

- name: RunSonarCloudTests
  displayName: Run Sonar Cloud Analysis
  type: boolean
  default: true

- name: RunMutationTests
  displayName: Run Mutation Tests
  type: boolean
  default: false

- name: RunACTests
  displayName: Run Acceptance Tests
  type: boolean
  default: false

variables:
  - group: vh-domains-and-urls
  - group: vh-apps-settings-generic
  - group: vh-preview
  - group: govuk-notify-preview

trigger:
  branches:
    include:
    - master
    - release/*
    - hotfix/*

pr:
  branches:
    include:
    - master

resources:
  repositories:
    - repository: templates
      type: github
      name: hmcts/azure-devops-templates
      ref: refs/heads/master
      endpoint: hmcts_shaed
  containers:
  - container: dotnetsdk
    image: sspublicsbox.azurecr.io/vh/dotnet:3.1.102
    endpoint: sspublicsbox
  - container: dotnetsdk-cipipeline
    image: sspublicsbox.azurecr.io/vh/dotnet-cipipeline:3.1.102
    endpoint: sspublicsbox

extends:
  template: stages\dotnet-package.yml@templates
  parameters:
    useNugetConfig: true
    nugetConfigPath: 
    coreProjectPath: VH.Core.Mapping
    nugetProjectPath: VH.Core.Mapping
    PackageNuget: ${{ parameters.PackageNuget }}
    PackageApp: ${{ parameters.PackageApp }}
    PackageAcceptanceTests: ${{ parameters.PackageACTests }}
    Test: ${{ or(parameters.RunUnitTests, parameters.RunIntegTests, parameters.RunMutationTests) }}
    testParameters:
      baseAgent: windows-latest
      coreProjectPath: VH.Core.Mapping
      useNugetConfig: true
      nugetConfigPath: VH.Core.Mapping
      unitTestProjectPath: VH.Core.Mapping.UnitTests
      secrets_KeyVault: $(pr_Secret_KeyVault)
      secrets_Subscription: $(pr_Secret_Subscription)
      RunUnitTests: ${{ parameters.RunUnitTests }}
      RunIntegrationTests: ${{ parameters.RunIntegTests }}
      RunSonarCloud: ${{ parameters.RunSonarCloudTests }}
      RunStryker: ${{ parameters.RunMutationTests }}
      coverletCoverageExclusions:
        - "[NotificationApi.*Tests?]*"
        - "[NotificationApi]Startup"
        - "[NotificationApi.Common]*"
        - "[Testing.Common]*"
      sonarCloud_ExtraProperties: |
        sonar.cs.opencover.reportsPaths=$(Common.TestResultsDirectory)/Coverage/coverage.opencover.xml
        sonar.coverage.exclusions=**/NotificationApi/Swagger/**/*,**/Program.cs,**/Startup.cs,**/Testing.Common/**/*,**/NotificationApi.Common/**/*,**/NotificationApi.IntegrationTests/**/*,**/NotificationApi.UnitTests/**/*,**/NotificationApi/Extensions/*,**/NotificationApi.DAL/Migrations/**/*
        sonar.cpd.exclusions=**/Program.cs,**/Startup.cs,**/Testing.Common/**/*,**/NotificationApi/Swagger/**/*,NotificationApi/NotificationApi.DAL/Migrations/*
      StrykerBreak: 75
    ACTest: ${{ parameters.RunACTests }}
